export const bids = [
  {
    bidId: '97991',
    title: 'Hoover Steam Vac',
    fund: 'Enterprise',
    amount: '$27.00',
  },
  {
    bidId: '97990',
    title: 'Table',
    fund: 'General Fund',
    amount: '$6.00',
  },
  {
    bidId: '97989',
    title: 'Table',
    fund: 'General Fund',
    amount: '$6.00',
  },
  {
    bidId: '97988',
    title: 'Table',
    fund: 'General Fund',
    amount: '$1.00',
  },
  {
    bidId: '97987',
    title: 'Swann Security System',
    fund: 'Enterprise',
    amount: '$218.00',
  },
  {
    bidId: '97986',
    title: 'Sony Laptop',
    fund: 'Enterprise',
    amount: '$283.00',
  },
  {
    bidId: '97985',
    title: 'XBox 360',
    fund: 'Enterprise',
    amount: '$33.00',
  },
  {
    bidId: '97983',
    title: 'Apple iPad',
    fund: 'Enterprise',
    amount: '$103.00',
  },
  {
    bidId: '97982',
    title: 'Canon EOS 7D Digital Camera',
    fund: 'Enterprise',
    amount: '$570.00',
  },
  {
    bidId: '97981',
    title: '2 Lorex Digital Wireless Cameras',
    fund: 'Enterprise',
    amount: '$62.00',
  },
  {
    bidId: '97980',
    title: '2 Cobra Walkie Talkies',
    fund: 'Enterprise',
    amount: '$47.00',
  },
  {
    bidId: '97979',
    title: 'Flips Audio Head Phones',
    fund: 'Enterprise',
    amount: '$42.00',
  },
  {
    bidId: '97978',
    title: 'Beats by Dr. Dre Head Phones',
    fund: 'Enterprise',
    amount: '$111.00',
  },
  {
    bidId: '98021',
    title: 'Kent Bicycle',
    fund: 'General Fund',
    amount: '$42.00',
  },
  {
    bidId: '98020',
    title: 'Kent Bicycle',
    fund: 'General Fund',
    amount: '$47.00',
  },
  {
    bidId: '98019',
    title: 'Diamond Back Bicycle',
    fund: 'General Fund',
    amount: '$39.00',
  },
  {
    bidId: '98017',
    title: 'Nishiki 21-Speed Bicycle',
    fund: 'General Fund',
    amount: '$53.00',
  },
  {
    bidId: '98016',
    title: 'Pacific 21-Speed Bicycle',
    fund: 'General Fund',
    amount: '$25.00',
  },
  {
    bidId: '98015',
    title: 'Next 14-Speed Bicycle',
    fund: 'General Fund',
    amount: '$21.00',
  },
  {
    bidId: '98014',
    title: 'Breezer 24-Speed Bicycle',
    fund: 'General Fund',
    amount: '$209.00',
  },
  {
    bidId: '98013',
    title: 'GMC 21-Speed Bicycle',
    fund: 'General Fund',
    amount: '$57.00',
  },
  {
    bidId: '98012',
    title: 'Magna 15-Speed Bicycle',
    fund: 'General Fund',
    amount: '$27.00',
  },
  {
    bidId: '98011',
    title: 'Dell Laptop',
    fund: 'General Fund',
    amount: '$118.50',
  },
  {
    bidId: '98010',
    title: 'Dell Laptop',
    fund: 'General Fund',
    amount: '$88.05',
  },
  {
    bidId: '98009',
    title: 'Dell Laptop',
    fund: 'General Fund',
    amount: '$84.00',
  },
  {
    bidId: '98008',
    title: 'Office Supplies',
    fund: '108070',
    amount: '$21.00',
  },
  {
    bidId: '98006',
    title: 'Printer',
    fund: 'General Fund',
    amount: '$52.00',
  },
  {
    bidId: '98005',
    title: 'Printer',
    fund: 'General Fund',
    amount: '$50.00',
  },
  {
    bidId: '98004',
    title: 'Printer',
    fund: 'General Fund',
    amount: '$45.00',
  },
  {
    bidId: '98003',
    title: 'Printer',
    fund: 'General Fund',
    amount: '$42.00',
  },
  {
    bidId: '98002',
    title: 'Microwave',
    fund: 'General Fund',
    amount: '$22.89',
  },
  {
    bidId: '98001',
    title: 'Microwave',
    fund: 'General Fund',
    amount: '$20.01',
  },
  {
    bidId: '98000',
    title: 'Printer',
    fund: 'General Fund',
    amount: '$40.50',
  },
  {
    bidId: '97999',
    title: 'Lamp',
    fund: 'General Fund',
    amount: '$11.00',
  },
  {
    bidId: '97998',
    title: '3 Chairs',
    fund: ' ',
    amount: '$2.00',
  },
  {
    bidId: '97995',
    title: 'Binders',
    fund: 'General Fund',
    amount: '$4.00',
  },
  {
    bidId: '97994',
    title: '3 Chairs',
    fund: ' ',
    amount: '$4.00',
  },
  {
    bidId: '97993',
    title: 'Popcorn Popper w/Stand',
    fund: 'Enterprise',
    amount: '$130.00',
  },
  {
    bidId: '98045',
    title: 'Electric Impact Wrench',
    fund: 'Enterprise',
    amount: '$42.00',
  },
  {
    bidId: '98044',
    title: 'DeWalt VSR Versa-Clutch Screwdriver',
    fund: 'Enterprise',
    amount: '$20.00',
  },
  {
    bidId: '98043',
    title: '"Black & Decker 1/2"" Electric Impact Wrench"',
    fund: 'Enterprise',
    amount: '$29.02',
  },
  {
    bidId: '98042',
    title: 'Hilti Angle Grinder',
    fund: 'Enterprise',
    amount: '$21.00',
  },
  {
    bidId: '98041',
    title: 'AmBico Bag w/Camera Accessories',
    fund: 'Enterprise',
    amount: '$32.60',
  },
  {
    bidId: '98040',
    title: 'Innova Car Scan',
    fund: 'Enterprise',
    amount: '$201.00',
  },
  {
    bidId: '98039',
    title: 'Tool Box w/Tools',
    fund: 'Enterprise',
    amount: '$54.26',
  },
  {
    bidId: '98029',
    title: 'Copier',
    fund: 'Enterprise',
    amount: '$113.00',
  },
  {
    bidId: '98027',
    title: 'Mixer',
    fund: 'Enterprise',
    amount: '$870.00',
  },
  {
    bidId: '98025',
    title: 'Ice Maker',
    fund: 'Enterprise',
    amount: '$640.00',
  },
  {
    bidId: '98024',
    title: 'Ice Cream Box',
    fund: 'Enterprise',
    amount: '$2.00',
  },
  {
    bidId: '98023',
    title: 'Refrigerator',
    fund: 'Enterprise',
    amount: '$106.01',
  },
  {
    bidId: '98022',
    title: 'Freezer',
    fund: 'Enterprise',
    amount: '$135.99',
  },
  {
    bidId: '98086',
    title: '2009 Chevolet Impala',
    fund: 'Enterprise',
    amount: '$164.00',
  },
  {
    bidId: '98085',
    title: '2008 Ford F-550',
    fund: 'Cashiers Check',
    amount: '"$6',
  },
  {
    bidId: '98084',
    title: '2005 CM Dakota 2 Stall Horse Trailer',
    fund: 'Cashiers Check',
    amount: '"$2',
  },
  {
    bidId: '98083',
    title: '2005 CM Dakota 2 Stall Horse Trailer',
    fund: 'Cashiers Check',
    amount: '"$2',
  },
  {
    bidId: '98077',
    title: 'Compaq Laptop',
    fund: 'Enterprise',
    amount: '$48.00',
  },
  {
    bidId: '98076',
    title: '2 PS3 Controllers',
    fund: 'Enterprise',
    amount: '$6.99',
  },
  {
    bidId: '98075',
    title: '"Dynex 60"" Tripod"',
    fund: 'Enterprise',
    amount: '$22.01',
  },
  {
    bidId: '98072',
    title: 'RCA Blu-ray Player',
    fund: 'Enterprise',
    amount: '$10.50',
  },
  {
    bidId: '98071',
    title: 'Sony Blu-ray Player',
    fund: 'Enterprise',
    amount: '$28.44',
  },
  {
    bidId: '98070',
    title: 'Apex DVD Player',
    fund: 'Enterprise',
    amount: '$13.00',
  },
  {
    bidId: '98068',
    title: 'Onkyo Receiver',
    fund: 'Enterprise',
    amount: '$97.99',
  },
  {
    bidId: '98062',
    title: 'Hoshizaki Ice Machine',
    fund: 'Enterprise',
    amount: '$311.00',
  },
  {
    bidId: '98061',
    title: 'Hoshizaki Ice Machine',
    fund: 'Enterprise',
    amount: '$311.00',
  },
  {
    bidId: '97961',
    title: '3 Televisions',
    fund: ' ',
    amount: '$15.01',
  },
  {
    bidId: '97960',
    title: '"Marantz 50"" Plasma Monitor"',
    fund: 'Enterprise',
    amount: '$10.11',
  },
  {
    bidId: '97959',
    title: '"Sanyo 55"" LCD TV"',
    fund: 'Enterprise',
    amount: '$362.44',
  },
  {
    bidId: '97958',
    title: '"Samsung 43"" Plasma TV"',
    fund: 'Enterprise',
    amount: '$93.00',
  },
  {
    bidId: '97957',
    title: '"Samsung 43"" Plasma TV"',
    fund: 'Enterprise',
    amount: '$57.00',
  },
  {
    bidId: '97956',
    title: '"Samsung 43"" Plasma TV"',
    fund: 'Enterprise',
    amount: '$96.00',
  },
  {
    bidId: '97955',
    title: 'Dell Monitor',
    fund: 'Enterprise',
    amount: '$13.00',
  },
  {
    bidId: '97954',
    title: 'Gateway Laptop',
    fund: 'Enterprise',
    amount: '$25.00',
  },
  {
    bidId: '97953',
    title: 'Weight Bench',
    fund: 'Enterprise',
    amount: '$103.00',
  },
  {
    bidId: '97952',
    title: 'Horizon Elliptical Machine',
    fund: 'Enterprise',
    amount: '$25.00',
  },
  {
    bidId: '97951',
    title: 'Weider Club Work Out Gym Set',
    fund: '3690389633',
    amount: '$190.00',
  },
  {
    bidId: '97950',
    title: 'Weight Bar w/Assorted Weights',
    fund: 'Enterprise',
    amount: '$195.00',
  },
  {
    bidId: '97949',
    title: '2 Weight Stands w/Weights',
    fund: '3690389631',
    amount: '$94.00',
  },
  {
    bidId: '97947',
    title: '"Samsung 40"" LED TV"',
    fund: 'Enterprise',
    amount: '$130.00',
  },
  {
    bidId: '97946',
    title: '"Hisense 40"" LED TV"',
    fund: 'Enterprise',
    amount: '$157.00',
  },
  {
    bidId: '98199',
    title: '"Chicago 7"" Tile Saw"',
    fund: 'Enterprise',
    amount: '$43.00',
  },
  {
    bidId: '98109',
    title: 'Whirlpool Washer & Dryer',
    fund: '3690663876',
    amount: '$225.46',
  },
  {
    bidId: '98107',
    title: 'Toshiba Laptop',
    fund: 'Enterprise',
    amount: '$91.00',
  },
  {
    bidId: '98105',
    title: '2 PS4 Games',
    fund: 'Enterprise',
    amount: '$11.00',
  },
  {
    bidId: '98104',
    title: '3 Ticket Booths',
    fund: ' ',
    amount: '$395.01',
  },
  {
    bidId: '98102',
    title: 'Battery Cart',
    fund: 'Enterprise',
    amount: '$42.00',
  },
  {
    bidId: '98094',
    title: 'Credenza',
    fund: 'General Fund',
    amount: '$57.00',
  },
  {
    bidId: '98129',
    title: 'Printer',
    fund: 'Enterprise',
    amount: '$52.00',
  },
  {
    bidId: '98128',
    title: 'Copier',
    fund: 'General Fund',
    amount: '$83.00',
  },
  {
    bidId: '98127',
    title: '2 Chairs',
    fund: 'Money Order',
    amount: '$4.00',
  },
  {
    bidId: '98126',
    title: 'Dell Laptop',
    fund: 'General Fund',
    amount: '$68.00',
  },
  {
    bidId: '98124',
    title: 'Dell Laptop',
    fund: 'General Fund',
    amount: '$68.00',
  },
  {
    bidId: '98123',
    title: 'Dell Laptop',
    fund: 'General Fund',
    amount: '$64.00',
  },
  {
    bidId: '98121',
    title: 'Dell Laptop',
    fund: 'General Fund',
    amount: '$74.04',
  },
  {
    bidId: '98119',
    title: 'Dell Laptop',
    fund: 'General Fund',
    amount: '$68.00',
  },
  {
    bidId: '98118',
    title: 'Dell Laptop',
    fund: 'General Fund',
    amount: '$106.00',
  },
  {
    bidId: '98113',
    title: 'Dell Computer',
    fund: 'General Fund',
    amount: '$81.01',
  },
  {
    bidId: '98112',
    title: 'Dell Computer',
    fund: 'General Fund',
    amount: '$79.88',
  },
  {
    bidId: '98111',
    title: 'Dell Computer',
    fund: 'General Fund',
    amount: '$84.00',
  },
  {
    bidId: '98110',
    title: 'Dell Computer',
    fund: 'General Fund',
    amount: '$90.88',
  },
  {
    bidId: '98260',
    title: '2004 Thomas School Bus',
    fund: 'Cashiers Check',
    amount: '"$1',
  },
  {
    bidId: '98259',
    title: '2004 Thomas School Bus',
    fund: 'Cashiers Check',
    amount: '"$1',
  },
  {
    bidId: '98258',
    title: '2004 Thomas School Bus',
    fund: 'Cashiers Check',
    amount: '"$2',
  },
  {
    bidId: '98256',
    title: '2001 Honda CBR 929RR',
    fund: 'Cashiers Check',
    amount: '"$1',
  },
  {
    bidId: '98255',
    title: '2005 Mercury Montego',
    fund: 'Enterprise',
    amount: '$945.00',
  },
  {
    bidId: '98250',
    title: '2004 Chevrolet Tahoe',
    fund: 'Cashiers Check',
    amount: '"$4',
  },
  {
    bidId: '98245',
    title: '2006 Infiniti M45',
    fund: 'Cashiers Check',
    amount: '"$3',
  },
  {
    bidId: '98242',
    title: '2005 Honda Civic',
    fund: '3690705447',
    amount: '"$1',
  },
  {
    bidId: '98149',
    title: 'Main Stays Bath Set',
    fund: 'Enterprise',
    amount: '$24.00',
  },
  {
    bidId: '98143',
    title: '2 Bongo Head Wraps',
    fund: 'Enterprise',
    amount: '$12.00',
  },
  {
    bidId: '98133',
    title: 'Husky Tool Bag w/Tools',
    fund: 'Enterprise',
    amount: '$35.00',
  },
  {
    bidId: '98132',
    title: 'Black & Decker Electric Weed Eater',
    fund: 'Enterprise',
    amount: '$13.26',
  },
  {
    bidId: '98269',
    title: '5 Extron Control Systems',
    fund: '105171',
    amount: '$25.00',
  },
  {
    bidId: '98268',
    title: 'Dayton Pallet Jack',
    fund: 'Enterprise',
    amount: '$78.85',
  },
  {
    bidId: '98262',
    title: 'White Industries Battery Charger',
    fund: 'Enterprise',
    amount: '$73.00',
  },
  {
    bidId: '98261',
    title: '5 Dollies',
    fund: '111100',
    amount: '$132.00',
  },
  {
    bidId: '98172',
    title: 'XBox 360',
    fund: 'Enterprise',
    amount: '$36.35',
  },
  {
    bidId: '98171',
    title: '5 Yamaha Surround Sound Speakers',
    fund: 'Enterprise',
    amount: '$34.00',
  },
  {
    bidId: '98168',
    title: 'Lenovo Laptop',
    fund: 'Enterprise',
    amount: '$117.00',
  },
  {
    bidId: '98167',
    title: 'Acer Laptop',
    fund: 'Enterprise',
    amount: '$32.00',
  },
  {
    bidId: '98166',
    title: 'Samsung Speaker',
    fund: 'Enterprise',
    amount: '$27.00',
  },
  {
    bidId: '98164',
    title: 'Sink',
    fund: 'Enterprise',
    amount: '$132.50',
  },
  {
    bidId: '98163',
    title: 'Cashier',
    fund: 'Enterprise',
    amount: '$103.00',
  },
  {
    bidId: '98162',
    title: '2 Rolling Carts',
    fund: 'Enterprise',
    amount: '$150.00',
  },
  {
    bidId: '98161',
    title: '2 Rolling Carts',
    fund: 'Enterprise',
    amount: '$240.00',
  },
  {
    bidId: '98159',
    title: 'CVap',
    fund: 'Enterprise',
    amount: '$106.00',
  },
  {
    bidId: '98158',
    title: 'CVap',
    fund: 'Enterprise',
    amount: '$431.00',
  },
  {
    bidId: '98157',
    title: 'CVap',
    fund: 'Enterprise',
    amount: '$411.00',
  },
  {
    bidId: '98156',
    title: 'File Cabinet',
    fund: 'General Fund',
    amount: '$21.00',
  },
  {
    bidId: '98155',
    title: 'File Cabinet',
    fund: 'General Fund',
    amount: '$20.30',
  },
  {
    bidId: '98154',
    title: 'File Cabinet',
    fund: 'General Fund',
    amount: '$16.00',
  },
  {
    bidId: '98153',
    title: 'Cabinet',
    fund: 'General Fund',
    amount: '$33.02',
  },
  {
    bidId: '98279',
    title: 'Nike Tennis Shoes Size: 11',
    fund: 'Enterprise',
    amount: '$51.57',
  },
  {
    bidId: '98276',
    title: 'Nike Tennis Shoes Size: 11.5',
    fund: 'Enterprise',
    amount: '$83.99',
  },
  {
    bidId: '98273',
    title: 'Nike Tennis Shoes Size: 11.5',
    fund: 'Enterprise',
    amount: '$84.00',
  },
  {
    bidId: '98203',
    title: '"Work Foce 24"" Bolt Cutters"',
    fund: 'Enterprise',
    amount: '$27.00',
  },
  {
    bidId: '98202',
    title: 'Canon Digital Camera',
    fund: 'Enterprise',
    amount: '$169.01',
  },
  {
    bidId: '98201',
    title: 'Bose Bluetooth Mobile Speaker',
    fund: 'Enterprise',
    amount: '$128.00',
  },
  {
    bidId: '98198',
    title: 'Auto Craft 2.25-Ton Floor Jack',
    fund: 'Enterprise',
    amount: '$51.00',
  },
  {
    bidId: '98195',
    title: 'Michael Kors Purse & Wallet',
    fund: 'Enterprise',
    amount: '$73.00',
  },
  {
    bidId: '98194',
    title: 'Michael Kors Wallet',
    fund: 'Enterprise',
    amount: '$86.00',
  },
  {
    bidId: '98190',
    title: 'Office Electronics',
    fund: '11091-',
    amount: '$26.50',
  },
  {
    bidId: '98188',
    title: 'Slide',
    fund: 'Enterprise',
    amount: '$240.00',
  },
  {
    bidId: '98187',
    title: 'Ice Maker',
    fund: 'Enterprise',
    amount: '$411.00',
  },
  {
    bidId: '98186',
    title: 'Freezer',
    fund: 'Enterprise',
    amount: '$382.00',
  },
  {
    bidId: '98185',
    title: 'Double Oven',
    fund: '3690975369',
    amount: '"$1',
  },
  {
    bidId: '98181',
    title: '4 Chairs',
    fund: '109700"',
    amount: '$37.00',
  },
  {
    bidId: '98177',
    title: 'Copier',
    fund: 'Enterprise',
    amount: '$173.00',
  },
  {
    bidId: '98336',
    title: '"10"" Kicker Subwoofers w/Kenwood Amplifier"',
    fund: 'Enterprise',
    amount: '$115.00',
  },
  {
    bidId: '98335',
    title: 'Laser Labs Tint Meter',
    fund: 'Enterprise',
    amount: '$21.00',
  },
  {
    bidId: '98333',
    title: 'Ridgid Collated Screwdriver',
    fund: 'Enterprise',
    amount: '$42.00',
  },
  {
    bidId: '98332',
    title: 'Glacier Bay Bathroom Faucet',
    fund: 'Enterprise',
    amount: '$35.00',
  },
  {
    bidId: '98323',
    title: 'Sony DVD Home Theater System',
    fund: 'Enterprise',
    amount: '$68.01',
  },
  {
    bidId: '98322',
    title: 'JVC Stereo Receiver',
    fund: 'Enterprise',
    amount: '$75.44',
  },
  {
    bidId: '98319',
    title: '"Hero 24"" Rims"',
    fund: 'Enterprise',
    amount: '$530.00',
  },
  {
    bidId: '98293',
    title: 'Serving Line',
    fund: 'Money Order',
    amount: '$239.00',
  },
  {
    bidId: '98289',
    title: 'Jordan Tennis Shoes Size: 11',
    fund: 'Enterprise',
    amount: '$70.01',
  },
  {
    bidId: '98288',
    title: 'Jordan Tennis Shoes Size: 11',
    fund: 'Enterprise',
    amount: '$75.99',
  },
  {
    bidId: '98287',
    title: 'Jordan Tennis Shoes Size: 11',
    fund: 'Enterprise',
    amount: '$132.00',
  },
  {
    bidId: '98284',
    title: 'Jordan Tennis Shoes Size: 11',
    fund: 'Enterprise',
    amount: '$89.01',
  },
  {
    bidId: '98283',
    title: 'Jordan Tennis Shoes Size: 11',
    fund: 'Enterprise',
    amount: '$160.00',
  },
  {
    bidId: '98218',
    title: 'Perforated Paper',
    fund: 'General Fund',
    amount: '$185.99',
  },
  {
    bidId: '98217',
    title: 'Television',
    fund: 'General Fund',
    amount: '$38.00',
  },
  {
    bidId: '98208',
    title: 'File Cabinet',
    fund: 'General Fund',
    amount: '$70.00',
  },
  {
    bidId: '98207',
    title: 'File Cabinet',
    fund: 'General Fund',
    amount: '$83.00',
  },
  {
    bidId: '98205',
    title: '2 Camcorders',
    fund: 'Cashiers Check',
    amount: '$156.00',
  },
  {
    bidId: '98204',
    title: 'File Cabinet',
    fund: 'General Fund',
    amount: '$37.13',
  },
  {
    bidId: '98385',
    title: 'Federal Signal Siren Amps (Emergency Provider Only)',
    fund: 'Enterprise',
    amount: '$25.00',
  },
  {
    bidId: '98384',
    title: '2006 Honda Ridgeline',
    fund: 'Cashiers Check',
    amount: '"$3',
  },
  {
    bidId: '98383',
    title: '1999 Honda Civic',
    fund: 'Cashiers Check',
    amount: '"$1',
  },
  {
    bidId: '98382',
    title: '2001 Dodge Durango',
    fund: '3691132411',
    amount: '"$1',
  },
  {
    bidId: '98376',
    title: '1998 Chevrolet Astro',
    fund: 'Cashiers Check',
    amount: '"$1',
  },
  {
    bidId: '98375',
    title: '"Samsung 46"" LED TV"',
    fund: 'Enterprise',
    amount: '$150.00',
  },
  {
    bidId: '98372',
    title: '"Samsung 51"" Plasma Smart TV"',
    fund: 'Enterprise',
    amount: '$202.18',
  },
  {
    bidId: '98346',
    title: '"Ryobi 7-1/4"" Miter Saw"',
    fund: 'Enterprise',
    amount: '$43.00',
  },
  {
    bidId: '98344',
    title: 'Husqvarna Back Pack Blower',
    fund: 'Enterprise',
    amount: '$160.01',
  },
  {
    bidId: '98235',
    title: 'Table',
    fund: 'General Fund',
    amount: '$22.01',
  },
  {
    bidId: '98233',
    title: '5 Chairs',
    fund: '109698',
    amount: '$19.00',
  },
  {
    bidId: '98225',
    title: '2 Chairs',
    fund: '3691257436',
    amount: '$20.00',
  },
  {
    bidId: '98223',
    title: 'Chair',
    fund: 'General Fund',
    amount: '$71.88',
  },
]
